CMake: Enable exception handling for compiler
LLVM isn't able to compile the compiler's code when exception
handling is not explicitly enabled:

error: cannot use 'throw' with exceptions disabled
       throw Exception();

The /EHsc flag has been added to TR_CXX_COMPILE_OPTIONS in the
cmake/platform/toolconfig/msvc.cmake file.

Warning C4291:

..\omr\OMR_Agent.cpp(145): warning C4291: 'void *OMR_Agent::operator
new(::size_t,void *)': no matching operator delete found; memory will
not be freed if initialization throws an exception
omr\include_core\OMR_Agent.hpp(136): note: see declaration of
'OMR_Agent::operator new'

has also been fixed.

Signed-off-by: Pavel Samolysov <samolisov@gmail.com>